language: python

dist: trusty
sudo: required

python:
  - 3.4
  - 3.5
  - 3.6

before_install:
  - sudo apt-get -q update
  - sudo apt-get install php5-cli php5-curl php5-common -y
  - "curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar"

script: 
  - "cd tests && python -m unittest discover;"
